# Working with External Libraries

In [2]:
import math

In [3]:
print("It's math! It has type {}".format(type(math)))

It's math! It has type <class 'module'>


In [5]:
print(dir(math))

['__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'copysign', 'cos', 'cosh', 'degrees', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'pi', 'pow', 'radians', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']


In [6]:
print("pi to 4 significant digits = {:.4}".format(math.pi))

pi to 4 significant digits = 3.142


In [7]:
math.log(32, 2)

5.0

In [9]:
help(math.log)

Help on built-in function log in module math:

log(...)
    log(x[, base])
    
    Return the logarithm of x to the given base.
    If the base not specified, returns the natural logarithm (base e) of x.



In [10]:
import math as mt

In [11]:
mt.pi

3.141592653589793

In [12]:
from math import *

In [13]:
print(pi, log(32, 2))

3.141592653589793 5.0


In [14]:
import numpy

In [15]:
print("numpy.random is a", type(numpy.random))

numpy.random is a <class 'module'>


In [16]:
print("it contains names such as...",
      dir(numpy.random)[-15:]
     )

it contains names such as... ['set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uniform', 'vonmises', 'wald', 'warnings', 'weibull', 'zipf']


In [19]:
rolls = numpy.random.randint(low=1, high=60, size=10)

In [20]:
rolls

array([12, 22, 42, 47, 49, 22,  5, 35, 19, 31])

In [21]:
type(rolls)

numpy.ndarray

In [22]:
print(dir(rolls))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift__', '__rmatmul__', '__

In [23]:
rolls.mean()

28.399999999999999

In [24]:
rolls.tolist()

[12, 22, 42, 47, 49, 22, 5, 35, 19, 31]

In [25]:
help(rolls.ravel)

Help on built-in function ravel:

ravel(...) method of numpy.ndarray instance
    a.ravel([order])
    
    Return a flattened array.
    
    Refer to `numpy.ravel` for full documentation.
    
    See Also
    --------
    numpy.ravel : equivalent function
    
    ndarray.flat : a flat iterator on the array.



In [26]:
rolls + 10

array([22, 32, 52, 57, 59, 32, 15, 45, 29, 41])

In [27]:
rolls <= 3

array([False, False, False, False, False, False, False, False, False, False], dtype=bool)

In [28]:
xlist = [[1,2,3],[2,4,6],]

In [29]:
x = numpy.asarray(xlist)

In [30]:
print("xlist = {}\nx =\n{}".format(xlist, x))

xlist = [[1, 2, 3], [2, 4, 6]]
x =
[[1 2 3]
 [2 4 6]]


In [31]:
x[1,-1]

6

In [1]:
!pip install tensorflow

    100% |████████████████████████████████| 59.4MB 372kB/s ta 0:00:011
    100% |████████████████████████████████| 24.5MB 833kB/s ta 0:00:011
    100% |████████████████████████████████| 1.2MB 5.2MB/s ta 0:00:011
    100% |████████████████████████████████| 573kB 7.3MB/s ta 0:00:01
    100% |████████████████████████████████| 3.0MB 3.2MB/s ta 0:00:011
    100% |████████████████████████████████| 1.7MB 1.4MB/s ta 0:00:011
    100% |████████████████████████████████| 51kB 6.1MB/s ta 0:00:01
    100% |████████████████████████████████| 61kB 3.7MB/s ta 0:00:01
    100% |████████████████████████████████| 102kB 5.5MB/s a 0:00:01
    100% |████████████████████████████████| 327kB 4.8MB/s eta 0:00:01
    100% |████████████████████████████████| 92kB 3.8MB/s ta 0:00:01
    100% |████████████████████████████████| 6.1MB 1.3MB/s ta 0:00:011
    100% |████████████████████████████████| 112kB 2.9MB/s ta 0:00:01
  Running setup.py bdist_wheel for termcolor ... done
  Stored in directory: /Users/simoneamorim/L

In [4]:
import tensorflow as tf

ModuleNotFoundError: No module named 'tensorflow'

In [35]:
a = tf.constant(1)

NameError: name 'tf' is not defined

In [36]:
pip install --upgrade pip


The following command must be run outside of the IPython shell:

    $ pip install --upgrade pip

The Python package manager (pip) can only be used from outside of IPython.
Please reissue the `pip` command in a separate terminal or command prompt.

See the Python documentation for more information on how to install packages:

    https://docs.python.org/3/installing/


In [40]:
print(dir(list))

['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']
